services:
  - type: web
    name: nexus-rag-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: API_CORS_ORIGINS
        value: https://nexusrag.vercel.app,http://localhost:3000
      - key: RENDER
        value: "true"
      - key: DISABLE_CROSS_ENCODER
        value: "true"
      - key: LLM_MODEL_NAME
        value: "gemini-2.0-flash"
      - key: SIMILARITY_THRESHOLD
        value: "0.1"
    healthCheckPath: /health
    plan: starter
    autoDeploy: true
