import test from 'node:test';
import assert from 'node:assert/strict';
import { handle } from '../../apps/gateway/src/preview-worker.js';
const workspace='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222';
const ids=['33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555'];
const env={SUPABASE_URL:'https://supabase.invalid',SUPABASE_PUBLISHABLE_KEY:'synthetic-public',SUPABASE_SERVICE_ROLE_KEY:'synthetic-secret',FRONTEND_ORIGIN:'https://frontend.invalid'};
const request=query=>new Request(`https://gateway.invalid/api/v1/workspaces/current/members${query}`,{headers:{authorization:'Bearer synthetic','x-workspace-id':workspace}});
function fixture(t,{count='*/203',revoke=false}={}){const calls=[];let memberships=0;t.mock.method(globalThis,'fetch',async (url,init={})=>{const u=new URL(url);calls.push({u,init});if(u.pathname==='/auth/v1/user')return Response.json({id:user});if(u.pathname==='/rest/v1/rpc/nexus_management_version')return Response.json({version:'036'});assert.equal(u.pathname,'/rest/v1/workspace_members');assert.equal(u.searchParams.get('workspace_id'),`eq.${workspace}`);if(u.searchParams.has('user_id')&&u.searchParams.get('user_id').startsWith('eq.')){memberships++;return Response.json(revoke&&memberships>1?[]:[{user_id:user,workspace_id:workspace,role:'owner'}]);}if(init.method==='HEAD'){assert.equal(init.headers.prefer,'count=exact');assert.equal(u.searchParams.get('select'),'user_id');assert.equal(u.searchParams.has('user_id'),false);return new Response(null,{headers:count?{'content-range':count}:{}});}const after=u.searchParams.get('user_id')?.slice(3);return Response.json(ids.filter(id=>!after||id>after).slice(0,Number(u.searchParams.get('limit'))).map(user_id=>({user_id,role:'viewer',profiles:{display_name:'Synthetic member'}})));});return calls;}
test('member roster uses exact workspace total and bounded keyset pages',async t=>{const calls=fixture(t);const first=await handle(request('?limit=2'),env);assert.equal(first.status,200);const a=await first.json();assert.equal(a.total,203);assert.equal(a.total_is_exact,true);assert.equal(a.members.length,2);assert.equal(a.next_after,ids[1]);assert.equal(a.members[0].display_name,'Synthetic member');const second=await handle(request(`?limit=2&after=${a.next_after}`),env);const b=await second.json();assert.equal(b.total,203);assert.equal(b.members.length,1);assert.equal(b.next_after,null);const reads=calls.filter(x=>x.u.searchParams.get('order'));assert.ok(reads.every(x=>x.u.searchParams.get('limit')==='3'&&x.u.searchParams.get('order')==='user_id.asc'));});
for(const query of ['?limit=0','?limit=101','?limit=2junk','?limit=-1','?after=','?after=or(user_id.not.is.null)'])test(`invalid roster pagination fails before data reads: ${query}`,async t=>{const calls=fixture(t);const r=await handle(request(query),env);assert.equal(r.status,422);assert.equal((await r.json()).error.code,'INVALID_SCOPE');assert.equal(calls.some(x=>x.init.method==='HEAD'||x.u.searchParams.has('order')),false);});
for(const count of [null,'*/9007199254740992','0-1/*'])test(`unavailable/unsafe exact member count fails closed: ${count}`,async t=>{fixture(t,{count});const r=await handle(request('?limit=2'),env);assert.equal(r.status,503);const b=await r.json();assert.equal(b.error.code,'PERSISTENCE_UNAVAILABLE');assert.equal(b.members,undefined);});
test('revoked membership cannot receive a late roster or its count',async t=>{fixture(t,{revoke:true});const r=await handle(request('?limit=2'),env);assert.equal(r.status,403);assert.equal((await r.json()).members,undefined);});
